// <auto-generated />
using System;
using HotelBooker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooker.Infrastructure.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251023165109_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooker.Domain.Entities.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13ab1a14-801b-419c-a388-0032ebb7adbb"),
                            AddressLine1 = "1200 Ocean View Drive",
                            AddressLine2 = "Tower B, Suite 10",
                            BookingRef = "A742",
                            City = "Santa Monica",
                            Country = "USA",
                            Name = "Pacific Shores Resort & Spa",
                            PostalCode = "90401",
                            Region = "CA"
                        },
                        new
                        {
                            Id = new Guid("77aeb7e5-5f9f-4913-9fc2-9f310d5102b5"),
                            AddressLine1 = "Threadneedle Street",
                            AddressLine2 = "City of London",
                            BookingRef = "B931",
                            City = "London",
                            Country = "UK",
                            Name = "The Royal Exchange Grand",
                            PostalCode = "EC2R 8AH",
                            Region = "England"
                        },
                        new
                        {
                            Id = new Guid("3e4eba53-7b38-4698-9740-8076d0d2957e"),
                            AddressLine1 = "25 Rue de Rivoli",
                            AddressLine2 = "",
                            BookingRef = "C1550",
                            City = "Paris",
                            Country = "France",
                            Name = "Le Petit Jardin Hotel",
                            PostalCode = "75004",
                            Region = "Île-de-France"
                        },
                        new
                        {
                            Id = new Guid("976eab2e-519e-48c8-8895-157946836f3b"),
                            AddressLine1 = "1 Chome-24-2 Nishi-Shinjuku",
                            AddressLine2 = "Shinjuku City",
                            BookingRef = "D33",
                            City = "Tokyo",
                            Country = "Japan",
                            Name = "Shinjuku Sky Tower Inn",
                            PostalCode = "160-0023",
                            Region = "Tokyo"
                        },
                        new
                        {
                            Id = new Guid("cb33a5de-772b-4c9e-920b-03e09417c78c"),
                            AddressLine1 = "142 George Street",
                            AddressLine2 = "The Rocks",
                            BookingRef = "E8802",
                            City = "Sydney",
                            Country = "Australia",
                            Name = "The Harbour View Residence",
                            PostalCode = "2000",
                            Region = "NSW"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
